# Generated by Django 5.2.1 on 2025-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('max_runs', models.IntegerField(default=1)),
                ('me', models.IntegerField(default=0)),
                ('te', models.IntegerField(default=0)),
                ('is_bpc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='planning', max_length=32)),
            ],
        ),
    ]
